name: Plugin Packages CI
on:
  push:
    branches:
      - 'master'
      - 'cert-manager-feature-branch'
    tags:
      - 'v*.*.*'
  pull_request:
    branches:
      - 'master'
      - 'cert-manager-feature-branch'

jobs:
  # pre-build job run golangci-lint
  go-lint:
    name: 'Golint'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Run golangci-lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: v1.30
          working-directory: ./cmd/

  helm:
    name: HelmLint
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2

      - name: Get repositories
        uses: hiberbee/github-action-helm@latest

      - name: Lint chart
        run: helm lint cockroachdb
        working-directory: .

  helmUnitTest:
    name: HelmTemplateTest
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test
        run: go test -v ./tests/template/...

  pre-build:
    name: build-self-signer-cert-utility
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: ladhaprafull/self-signer-utility:latest
          file: build/docker-image/Dockerfile
          build-args: RUN_ID=${{ github.run_id }},RUN_NUMBER=${{ github.run_number }}

  helm-integration:
    name: Helm-Integration-Test
    runs-on: ubuntu-latest
    needs:
      - pre-build
    steps:
      - name: Checkout sources
        uses: actions/checkout@v2
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Install Kind
        uses: helm/kind-action@v1.1.0
      - name: Setup Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.15
      - name: Test
        run: go test -v ./tests/integration/...
